# Production Alerting Rules

groups:
  - name: barreservas_production
    rules:
      # Critical Alerts
      - alert: ServiceDown
        expr: up{job="barreservas-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "BarReservas service is down"
          description: "Service has been down for more than 1 minute"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: DatabaseConnectionFailure
        expr: up{job="postgres"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Database connection failed"
          description: "Cannot connect to PostgreSQL database"

      # Warning Alerts
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow response time"
          description: "95th percentile response time is {{ $value }}s"

      # Business Logic Alerts
      - alert: HighReservationFailureRate
        expr: rate(reservations_failed_total[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High reservation failure rate"
          description: "{{ $value }} reservations failing per second"

      - alert: NoReservationsInHour
        expr: increase(reservations_created_total[1h]) == 0
        for: 1h
        labels:
          severity: info
        annotations:
          summary: "No reservations in the last hour"
          description: "This might indicate a problem or low traffic period"